server:
  host: "0.0.0.0"
  port: 8080

workerpool:
  num_workers: 4          # количество параллельных воркеров
  task_queue_size: 100    # размер канала задач

storage:
  downloads_dir: "downloads"  # папка для сохранения файлов

tasks:
  file: "tasks.json"      # файл для сохранения состояния задач